export const appRoutes = [
  '/',
  '/onboarding',
  '/today',
  '/roadmap',
  '/paths/:slug',
  '/lessons/:slug',
  '/practice',
  '/quiz',
  '/projects',
  '/leagues',
  '/quests',
  '/portfolio',
  '/resources',
  '/ai-mentor',
  '/notifications',
  '/admin',
  '/admin/content',
  '/admin/experiments',
  '/analytics',
] as const
